name: CI/CD Pipeline

on:
  push:
    branches: [master]
  workflow_dispatch:
    inputs:
      manual_rollback:
        description: "Commit SHA hoặc tag để rollback (để trống để deploy bình thường)"
        required: false

jobs:
  # 1. Build & Test
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      # - name: Run tests
      #   run: npm test

  # 2. Deploy to Production
  deploy:
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || (github.event_name == 'workflow_dispatch' && !github.event.inputs.manual_rollback) }}
    environment: staging
    env:
      NODE_ENV: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy via SSH & PM2
        id: ssh_deploy
        run: |
          sshpass -p "${{ secrets.STAGING_VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_VPS_USERNAME }}@${{ secrets.STAGING_VPS_IP_HOST }} << 'EOF'
            set -euo pipefail
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            source ~/.bashrc; source ~/.profile
            # Cài đặt jq nếu chưa có
            if ! command -v jq &> /dev/null; then
              sudo apt-get update && sudo apt-get install -y jq
            fi
            cd ${{ secrets.STAGING_PATH_PROJECT }}
            git fetch origin master && git reset --hard origin/master
            rm -rf .next node_modules
            npm ci && npm run build
            pm2 describe client-shopsifu &>/dev/null && pm2 restart client-shopsifu || pm2 start dist/main.js --name client-shopsifu
            # Thêm độ trễ để ứng dụng ghi log và PM2 cập nhật trạng thái
            sleep 12
            # Lấy trạng thái PM2 dưới dạng JSON
            pm2 jlist > /tmp/pm2_status.json
            # Lấy log
            pm2 logs client-shopsifu --lines 100 --nostream > /tmp/pm2_logs.txt
            STATUS=$(pm2 info client-shopsifu | grep status | awk '{print $4}')
            echo "$STATUS" > /tmp/app_status.txt
            if [[ "$STATUS" != "online" ]]; then
              exit 2
            fi
          EOF
        continue-on-error: true

      - name: Collect PM2 Output
        if: always()
        id: pm2_logs
        run: |
          sshpass -p "${{ secrets.STAGING_VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_VPS_USERNAME }}@${{ secrets.STAGING_VPS_IP_HOST }} << 'EOF'
            # Trích xuất thông tin từ pm2 jlist
            PM2_INFO=$(jq -r '.[] | select(.name == "client-shopsifu") | "Name: \(.name)\nStatus: \(.pm2_env.status)\nPID: \(.pid)\nUptime: \(.pm2_env.uptime // 0 | tostring + \"ms\")\nCPU: \(.monit.cpu)%\nMemory: \(.monit.memory / 1024 / 1024 | tostring + \"MB\")"' /tmp/pm2_status.json 2>/dev/null)
            if [ -z "$PM2_INFO" ]; then
              PM2_INFO="Không tìm thấy process client-shopsifu hoặc không thể lấy trạng thái PM2"
            fi
            echo "::set-output name=pm2_info::$PM2_INFO"
            # Lấy log, lọc bỏ dòng hệ thống
            if [ -f /tmp/pm2_logs.txt ]; then
              PM2_LOGS=$(grep -v '\[TAILING\]' /tmp/pm2_logs.txt | tail -n 100)
              if [ -z "$PM2_LOGS" ]; then
                PM2_LOGS="Không có log ứng dụng hoặc log rỗng"
              fi
            else
              PM2_LOGS="Không có log ứng dụng hoặc file log không tồn tại"
            fi
            echo "::set-output name=pm2_logs::$PM2_LOGS"
          EOF

      - name: Tag Release
        if: success()
        run: |
          TAG=v$(date +'%Y.%m.%d.%H%M%S')
          git tag $TAG
          git push origin $TAG

      - name: Get Commit Info
        id: commit_info
        run: |
          COMMIT_SHA=$(git rev-parse HEAD)
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          echo "commit_sha=$COMMIT_SHA" >> $GITHUB_OUTPUT
          echo "commit_message<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Discord Embed Notification
        if: always()
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          STATUS: ${{ job.status }}
          BRANCH: ${{ github.ref_name }}
          COMMIT: ${{ github.sha }}
          ACTOR: ${{ github.actor }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
          PM2_INFO: ${{ steps.pm2_logs.outputs.pm2_info }}
          PM2_LOGS: ${{ steps.pm2_logs.outputs.pm2_logs }}
          COMMIT_SHA: ${{ steps.commit_info.outputs.commit_sha }}
          COMMIT_MESSAGE: ${{ steps.commit_info.outputs.commit_message }}
        run: |
          # Kiểm tra DISCORD_WEBHOOK
          if [ -z "$DISCORD_WEBHOOK" ]; then
            echo "Lỗi: DISCORD_WEBHOOK không được đặt"
            exit 1
          else
            echo "DISCORD_WEBHOOK đã được đặt"
          fi

          # Cài đặt jq để xử lý JSON
          sudo apt-get update && sudo apt-get install -y jq

          COLOR=3066993
          ICON="✅"
          if [ "$STATUS" != "success" ]; then
            COLOR=15158332
            ICON="❌"
          fi

          # Thoát PM2_LOGS và PM2_INFO an toàn bằng jq
          ESCAPED_LOGS=$(echo "${PM2_LOGS:0:1500}" | jq -s -R .)
          ESCAPED_PM2_INFO=$(echo "$PM2_INFO" | jq -s -R .)
          ESCAPED_COMMIT_MESSAGE="$COMMIT_MESSAGE"

          # Tạo JSON payload bằng jq để đảm bảo cú pháp đúng
          JSON_PAYLOAD=$(jq -n \
            --arg status "$STATUS" \
            --arg icon "$ICON" \
            --arg branch "$BRANCH" \
            --arg commit "$COMMIT" \
            --arg commit_sha "$COMMIT_SHA" \
            --arg commit_message "$ESCAPED_COMMIT_MESSAGE" \
            --arg repo "$REPO" \
            --arg actor "$ACTOR" \
            --arg pm2_info "$ESCAPED_PM2_INFO" \
            --arg logs "$ESCAPED_LOGS" \
            --arg run_id "$RUN_ID" \
            --arg color "$COLOR" \
            '{
              embeds: [{
                title: "🚀 CLIENT - Thông báo triển khai",
                color: ($color | tonumber),
                fields: [
                  { name: "Trạng thái", value: "\($icon) \($status)", inline: true },
                  { name: "Nhánh", value: "`\($branch)`", inline: true },
                  { name: "Commit", value: "[`\($commit)`](https://github.com/\($repo)/commit/\($commit))", inline: false },
                  { name: "Commit SHA", value: "`\($commit_sha)`", inline: false },
                  { name: "Commit Message", value: $commit_message, inline: false },
                  { name: "Người thực hiện", value: "`\($actor)`", inline: true },
                  { name: "Trạng thái PM2", value: "```\n\($pm2_info)\n```", inline: false }
                ],
                description: "**100 dòng log cuối:**\n```\n\($logs)\n```",
                url: "https://github.com/\($repo)/actions/runs/\($run_id)"
              }]
            }')

          # Ghi log payload để kiểm tra
          echo "JSON Payload: $JSON_PAYLOAD"

          # Gửi yêu cầu và ghi lại phản hồi
          RESPONSE=$(curl -s -w "%{http_code}" -H "Content-Type: application/json" -X POST -d "$JSON_PAYLOAD" "$DISCORD_WEBHOOK")
          HTTP_CODE=${RESPONSE: -3}
          RESPONSE_BODY=${RESPONSE%???}

          echo "Mã trạng thái HTTP: $HTTP_CODE"
          echo "Nội dung phản hồi: $RESPONSE_BODY"

          if [ "$HTTP_CODE" != "204" ]; then
            echo "Lỗi: Không thể gửi thông báo Discord"
            exit 1
          fi

  # 3. Automatic Rollback on Failure
  rollback-auto:
    name: Automatic Rollback
    needs: deploy
    runs-on: ubuntu-latest
    if: needs.deploy.result == 'failure'
    steps:
      - name: Rollback to previous commit on server
        run: |
          sshpass -p "${{ secrets.STAGING_VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_VPS_USERNAME }}@${{ secrets.STAGING_VPS_IP_HOST }} << 'EOF'
            set -euo pipefail
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            source ~/.bashrc; source ~/.profile
            cd ${{ secrets.STAGING_PATH_PROJECT }}
            git fetch origin master
            git reset --hard HEAD~1
            rm -rf dist node_modules
            npm ci && npm run build
            pm2 restart client-shopsifu
          EOF

  # 4. Manual Rollback
  manual-rollback:
    name: Manual Rollback
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.manual_rollback
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specific commit/tag
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.manual_rollback }}

      - name: Re-deploy to VPS
        run: |
          sshpass -p "${{ secrets.STAGING_VPS_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.STAGING_VPS_USERNAME }}@${{ secrets.STAGING_VPS_IP_HOST }} << 'EOF'
            set -euo pipefail
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
            source ~/.bashrc; source ~/.profile
            cd ${{ secrets.STAGING_PATH_PROJECT }}
            git reset --hard HEAD
            rm -rf dist node_modules
            npm ci && npm run build
            pm2 restart client-shopsifu
          EOF

permissions:
  contents: write