export const PAYMENT_QUEUE_NAME = 'payment'
export const CANCEL_PAYMENT_JOB_NAME = 'cancel-payment'
export const SHIPPING_QUEUE_NAME = 'shipping'
export const CREATE_SHIPPING_ORDER_JOB = 'create-shipping-order'
export const PROCESS_GHN_WEBHOOK_JOB = 'process-ghn-webhook'
export const CANCEL_GHN_ORDER_JOB = 'cancel-ghn-order'
export const CREATE_GHN_ORDER_JOB = 'create-ghn-order'
